version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mercon-app
    restart: unless-stopped
    depends_on:
      - postgres
    env_file:
      - .env
    networks:
      - mercon-network

  postgres:
    image: postgres:15-alpine
    container_name: mercon-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-mercon}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - mercon-network

networks:
  mercon-network:
    driver: bridge

volumes:
  postgres-data: 